export const MOVIES = [
  {
    id: 1,
    title: "33 слова о дизайне",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 2,
    title: "Киноальманах «100 лет дизайна»",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
  {
    id: 3,
    title: "В погоне за Бенкси",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
  {
    id: 5,
    title: "Баския: Взрыв реальности",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 6,
    title: "Бег это свобода",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 7,
    title: "Книготорговцы",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 8,
    title: "Когда я думаю о Германии ночью",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
  {
    id: 9,
    title: "Gimme Danger: История Игги и The Stooges",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 10,
    title: "Дженис: Маленькая девочка грустит",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
  {
    id: 11,
    title: "Соберись перед прыжком",
    duration: "1ч 17м",
    isSaved: true,
    url: "",
  },
  {
    id: 12,
    title: "Пи Джей Харви: A dog called money",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
  {
    id: 4,
    title: "По волнам: Искусство звука в кино",
    duration: "1ч 17м",
    isSaved: false,
    url: "",
  },
];
